### ISSUE TITLE
とりあえず動かしてみる

### ISSUE THREAD

**Issue by srpkdyy** [wacha-dev/desktop-mmd-character#1]

**Comment by srpkdyy** [comment]
@Masa512411 
とりあえずCloneしてVisualStdioで開いて動かしてみて
消すときは Alt+F4 で消せる。
終わったらIssueをCloseしてみて。

**Comment by srpkdyy** [comment]
@upnt

**Comment by Masa512411** [comment]
ペンギン召喚してみました

**Comment by srpkdyy** [comment]
@Masa512411 
awesome !
@upnt いつできるかわからんし、Closeしちゃおっか

**Comment by srpkdyy** [comment]
@upnt 動作確認終わりました？
